services:
  nginx:
    build:
      context: ./frontend
    container_name: "nginx"
    depends_on:
        - backend
    ports:
        # host:container
        - "8000:80"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: "backend"
    expose:
      # expose port 8000 to other containers
      - 8000
    restart: always
