services:
  nginx:
    build:
      context: ./frontend
    container_name: "nginx"
    depends_on:
        - backend
    links:
        - backend
    ports:
        # host : container
        - "8000:80"

  backend:
    build:
      context: ./backend
    container_name: "backend"
