services:
  nginx:
      image: nginx
      container_name: "nginx"
      depends_on:
        - frontend
        - backend
      links:
        - backend
      volumes:
        - shared:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        # host : container
        - "8080:80"
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    volumes:
      - shared:/app/dist/heating-pump-tools/
  backend:
    build:
      context: ./backend
    container_name: "backend"

volumes:
  shared: {}
